#!/bin/bash
pattern='/\G[^\x00-\x7F]/gm'
artist=$(playerctl metadata --format '{{ artist }}')
count=$(echo -n "$artist" | wc -c)
if [ -z "$artist" ]; then
	echo "Not Playing";
else
	if [ "$count" -le 20 ]; then
        echo $artist
	else
		if [[ "$artist" =~ [^\x00-\x7F] ]]; then
			echo $(playerctl metadata --format '{{ artist }} ' | awk '{ print substr($0, 1, 10) }')...
        elif [[ "$artist" -le 15 ]]; then
            echo $(playerctl metadata --format '{{ artist }} ' | awk '{print $1, $2}')
        else
	    	echo $(playerctl metadata --format '{{ artist }}' | awk '{print $1, $2, $3}')...
		fi
	fi
fi