#!/bin/bash

dir="~/.config/rofi/powermenu"

# Confirmation
confirm_exit() {
  rofi -dmenu\
    -i\
    -no-fixed-num-lines\
    -p "Are you sure? : "\
    -theme $dir/confirm.rasi
}

# Messages
msg() {
  rofi -theme "$dir/message.rasi" -e "Available Options  -  yes / y / no / n"
}


case $1 in
    shutdown)
			systemctl poweroff
    ;;
    reboot)
			systemctl reboot
    ;;
    lock)
			eww close-all
			if [[ -f /usr/bin/light-locker ]]; then
				light-locker-command -l
			elif [[ -f /usr/bin/betterlockscreen ]]; then
				betterlockscreen -l
			fi
    ;;
    suspend)
			eww close-all
			systemctl suspend
			light-locker-command -l
    ;;
    logout)
			eww close-all
			if [[ "$DESKTOP_SESSION" == "Openbox" ]]; then
				openbox --exit
			elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
				bspc quit
			elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
				i3-msg exit
			fi
    ;;
esac