#!/usr/bin/env bash
set -euo pipefail

if [ -p /tmp/vol ] && [ -p /tmp/vol-icon ]; then
    true
else
    mkfifo /tmp/vol && echo "$(pulsemixer --get-volume | awk '{print $1}')" > /tmp/vol 
    mkfifo /tmp/vol-icon && ~/.config/sxhkd/scripts/eww_vol_icon
fi

script_name="eww_vol"
for pid in $(pgrep -f $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

start=$SECONDS
value=2

eww_wid="$(xdotool search --name 'Eww - volume' || true)"

if [ ! -n "$eww_wid" ]; then
    eww open volume
    eww_wid="$(xdotool search --name 'Eww - volume' || true)"
fi

case $1 in
    up)
        currentVolume=$(pulsemixer --get-volume | awk '{print $1}')
               if [[ "$currentVolume" -ge "100" ]]; then
                   pulsemixer --max-volume 100
               else
                   pulsemixer --change-volume +"$value"
               fi
    ;;
    down)
        pulsemixer --change-volume -"$value"
    ;;
    mute)
       pulsemixer --toggle-mute
    ;;
esac

echo $(pulsemixer --get-volume | awk '{print $1}') > /tmp/vol 
~/.config/sxhkd/scripts/eww_vol_icon

while [ -n "$eww_wid" ]; do
    duration=$(( SECONDS - start ))
    if [[ $duration -gt 1 ]]; then
        eww close volume
        eww_wid="$(xdotool search --name 'Eww - volume' || true)"       
    fi
    sleep 0.2
done
