#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         	2
bspc config window_gap          	18
bspc config split_ratio          	0.50

bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config paddingless_monocle 	true
bspc config single_monocle 				false
# bspc config focus_follows_pointer true


bspc config focused_border_color "#ff6188"
bspc config normal_border_color "#2f2f2f"

bspc rule -a Krita desktop='^6' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating
bspc rule -a dolphin state=floating
bspc rule -a "spotify" state=floating

# Kill if already running
killall -9 sxhkd dunst light-locker picom
eww kill

# Java Applications
wmname LG3D

# Startup Apps
numlockx on
sxhkd &
light-locker &
picom --experimental-backends &
nitrogen --restore
dunst &
sh ~/.config/polybar/launch.sh
eww daemon &
