format = "$all"

scan_timeout = 60
add_newline = false

[cmd_duration]
format = "[$duration]($style)"

[status]
disabled = false
format = "[$symbol $status]($style)"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"

[java]
format = "[${symbol}(${version} )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

